name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VITE_API_ORIGIN: http://localhost:3000
      VITE_API_PATH: /api/v1/trpc

      EMAIL: ${{ secrets.EMAIL }}
      EMAIL_APP_PASS: ${{ secrets.EMAIL_APP_PASS }}

      CLIENT_ID_GITHUB: ${{ secrets.CLIENT_ID_GITHUB }}
      CLIENT_SECRET_GITHUB: ${{ secrets.CLIENT_SECRET_GITHUB }}

      CLIENT_ID_GOOGLE: ${{ secrets.CLIENT_ID_GOOGLE }}
      CLIENT_SECRET_GOOGLE: ${{ secrets.CLIENT_SECRET_GOOGLE }}

      BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
      BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }}

      AWS_ACCESS_ID_KEY: ${{ secrets.AWS_ACCESS_ID_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      AWS_S3_REGION: ${{ secrets.AWS_S3_REGION }}
      AWS_S3_EMAIL_TEMPLATES_BUCKET_NAME: ${{ secrets.AWS_S3_EMAIL_TEMPLATES_BUCKET_NAME }}

      FRONT_END_URL: ${{ secrets.FRONT_END_URL }}
      FRONT_END_FULL_URL: ${{ secrets.FRONT_END_FULL_URL }}

      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    services:
      postgres:
        image: postgres:17.6-alpine
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.17.0
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Type check server
        run: npm run typecheck -w=server

      - name: Type check client
        run: npm run typecheck -w=client

      - name: Lint server
        run: npm run lint -w=server

      - name: Lint client
        run: npm run lint -w=client

      - name: Test client (unit)
        run: npm run test:unit -w=client

      - name: Run server database migrations
        run: npm run migrate:latest -w=server

      - name: Test server
        run: npm test -w=server

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Start server for E2E tests
        run: npm run dev -w=server &

      - name: Build front-end for E2E tests
        run: npm run build -w=client

      - name: Wait for server to startup
        uses: jtalk/url-health-check-action@v4
        with:
          max-attempts: 5
          retry-delay: 5s
          url: ${{ env.VITE_API_ORIGIN }}/api/health

      - name: Test client E2E
        run: npm run test:e2e -w=client
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: client/playwright-report/
          retention-days: 7
